# sudo: required

# # not really necessary
# services:
#   - docker

# # images already built in github package repository
# deploy:
#   on:
#     branch: master
#   provider: elasticbeanstalk
#   region: us-west-1
#   app: multi-docker
#   env: MultiDocker-env
#   bucket_name: elasticbeanstalk-us-west-1-306476627547
#   bucket_path: docker-multi
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: $AWS_SECRET_KEY
