sudo: required

# not really necessary
services:
  - docker

# images already built in github package repository
deploy:
  on:
    branch: master
  provider: elasticbeanstalk
  region: 'ap-northeast-1'
  app: 'Mail App'
  env: 'MailApp-env'
  bucket_name: 'elasticbeanstalk-ap-northeast-1-263985093748'
  access_key_id:
    secure: $ACCESS_KEY_ID
  secret_access_key:
    secure: $SECRET_ACCESS_KEY
