version: '3'
services:
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - '4200:80'
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/app/node_modules
      - ./frontend:/usr/app
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/app/node_modules
      - ./backend:/usr/app
