version: '3'
services:
  # Stripe Cli (forward stripe webhooks events to backend)
  # stripe:
  #   restart: always
  #   image: stripe/stripe-cli
  # stripe listen --forward-to localhost:3000/api/stripe-webhook

  # Nginx
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    image: mail-nginx:dev
    ports:
      - '4200:80'

  # Frontend
  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    image: mail-frontend:dev
    volumes:
      - /usr/app/node_modules
      - ./frontend:/usr/app

  # Backend
  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    image: mail-backend:dev
    volumes:
      - /usr/app/node_modules
      - ./backend:/usr/app
