branch-defaults:
  master:
    environment: Mail-env
  develop:
    environment: Mail-env-develop
deploy:
  artifact: Dockerrun.aws.json
global:
  application_name: Mail
  default_ec2_keyname: null
  default_platform: Multi-container Docker running on 64bit Amazon Linux/2.17.0
  default_region: ap-northeast-1
  profile: null
