name: Build and Deploy

on:
  push:
    branches:
      - 'master'
      - 'releases/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GITHUB_ID: ${{ secrets.GITHUB_ID }}
      GITHUB_PACKAGE_REGISTRY_TOKEN: ${{ secrets.GITHUB_PACKAGE_REGISTRY_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v1
      # - name: Build images
      #   run: bash docker-build.sh

      # - name: Push images to GPR
      #   run: |
      #     docker login docker.pkg.github.com -u $GITHUB_ID -p $GITHUB_PACKAGE_REGISTRY_TOKEN
      #     docker tag xinyangyuan/mail-nginx docker.pkg.github.com/xinyangyuan/mail/nginx:latest
      #     docker tag xinyangyuan/mail-frontend docker.pkg.github.com/xinyangyuan/mail/frontend:latest
      #     docker tag xinyangyuan/mail-backend docker.pkg.github.com/xinyangyuan/mail/backend:latest
      #     docker push docker.pkg.github.com/xinyangyuan/mail/nginx:latest
      #     docker push docker.pkg.github.com/xinyangyuan/mail/frontend:latest
      #     docker push docker.pkg.github.com/xinyangyuan/mail/backend:latest

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v1
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: Mail
          environment_name: Mail-env
          version_label: 5
          region: ap-northeast-1
          deployment_package: Dockerrun.aws.json
