name: Build and Deploy

on:
  push:
    branches:
      - develop
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    env:
      GPR: docker.pkg.github.com/xinyangyuan/mail
      GITHUB_ID: ${{ secrets.GITHUB_ID }}
      GITHUB_PACKAGE_REGISTRY_TOKEN: ${{ secrets.GITHUB_PACKAGE_REGISTRY_TOKEN }}

    steps:
      - name: Pull source
        uses: actions/checkout@v1

      - name: Build images
        run: |
          docker build -t $GPR/nginx:latest -t $GPR/nginx:$GITHUB_SHA ./nginx
          docker build -t $GPR/frontend:latest -t $GPR/frontend:$GITHUB_SHA ./frontend
          docker build -t $GPR/backend:latest -t $GPR/backend:$GITHUB_SHA ./backend

      - name: Login to Github-Registry (GPR)
        run: echo $GITHUB_PACKAGE_REGISTRY_TOKEN | docker login docker.pkg.github.com -u $GITHUB_ID --password-stdin

      - name: Push images to Github-Registry (GPR)
        run: |
          docker push $GPR/nginx:latest
          docker push $GPR/frontend:latest
          docker push $GPR/backend:latest
          docker push $GPR/nginx:$GITHUB_SHA
          docker push $GPR/frontend:$GITHUB_SHA
          docker push $GPR/backend:$GITHUB_SHA

  deploy:
    name: Deploy to AWS EB
    runs-on: ubuntu-latest
    needs: build

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Pull source
        uses: actions/checkout@v1

      - name: Setup eb-cli
        run: pip install awsebcli --upgrade --user

      - name: Check eb-cli installation
        run: ~/.local/bin/eb --version

      - name: Config eb credentials
        run: |
          mkdir ~/.aws | true
          echo "[default] " > ~/.aws/credentials
          echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
          echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials

      - name: Deploy to EB (Develop Branch)
        if: github.ref == 'refs/heads/develop'
        run: ~/.local/bin/eb deploy Mail-env-develop -l $GITHUB_SHA

      - name: Deploy to EB (Master on Release)
        if: github.event_name == 'release'
        run: ~/.local/bin/eb deploy Mail-env -l $GITHUB_SHA
